name: CI

on:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened ]

jobs:
  integration:
    name: Integration Checks
    runs-on: ubuntu-latest

    # 3.8 used by AWS Lambda, 3.9 as latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install safety
        pip install bandit
        pip install -r requirements.txt

    - name: Run Tests (PyTest)
      run: pytest

    - name: Linting Check (PyLint)
      run: pylint -j 0 lambda_function.py LTVCalculator.py

    - name: Safety Check
      run: safety check -r requirements.txt

    - name: Bandit Code Vulnerability Check (Excluding Unit Tests)
      run: bandit -r . -x ./test/
