name: Continuous Deployment (dev)

on:
  push: 
    branches: [ develop ]

jobs:
  deploydev:
    name: AWS Lambda Deployment (dev)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python v3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: pytest

    - name: Create Zip file
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r ./bundle.zip lambda_function.py LTVCalculator.py

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Deploy to Lambda
      run: aws lambda update-function-code --function-name cetm67_ass2-ltvcalculator --zip-file fileb://bundle.zip
