name: Deploy to AWS Lambda
on: 
  push:
    branches:
      - main
jobs:
  deploy_source:
    name: Build and Deploy Lambda
    strategy:
      matrix:
        python-version: [3.8]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          CI: true
      - name: Test with pytest
        run: pytest
      - name: Create Zip file
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip lambda_function.py LTVCalculator.py
      - name: Deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-west-2
          function_name: cetm67_ass2-ltvcalculator
          zip_file: bundle.zip
